---

- name: Ensure Chezmoi installed
  pacman:
    name: chezmoi
    state: present

- name: Install Chezmoi dotfiles
  shell: "chezmoi init --apply {{ chezmoi__github_user }}"
  register: chezmoi
  become: yes
  become_user: alex
  changed_when: "'Cloning into' in chezmoi.stderr"
